package com.arcas0803.device_permission

object PermissionConstants {
    const val LOG_TAG = "permissions_handler"
    const val PERMISSION_CODE = 24
    const val PERMISSION_CODE_IGNORE_BATTERY_OPTIMIZATIONS = 209
    const val PERMISSION_CODE_MANAGE_EXTERNAL_STORAGE = 210
    const val PERMISSION_CODE_SYSTEM_ALERT_WINDOW = 211
    const val PERMISSION_CODE_REQUEST_INSTALL_PACKAGES = 212
    const val PERMISSION_CODE_ACCESS_NOTIFICATION_POLICY = 213
    const val PERMISSION_CODE_SCHEDULE_EXACT_ALARM = 214

    const val PERMISSION_GROUP_CALENDAR = 0
    const val PERMISSION_GROUP_CAMERA = 1
    const val PERMISSION_GROUP_CONTACTS = 2
    const val PERMISSION_GROUP_LOCATION = 3
    const val PERMISSION_GROUP_LOCATION_ALWAYS = 4
    const val PERMISSION_GROUP_LOCATION_WHEN_IN_USE = 5
    const val PERMISSION_GROUP_MEDIA_LIBRARY = 6
    const val PERMISSION_GROUP_MICROPHONE = 7
    const val PERMISSION_GROUP_PHONE = 8
    const val PERMISSION_GROUP_PHOTOS = 9
    const val PERMISSION_GROUP_PHOTOS_ADD_ONLY = 10
    const val PERMISSION_GROUP_REMINDERS = 11
    const val PERMISSION_GROUP_SENSORS = 12
    const val PERMISSION_GROUP_SMS = 13
    const val PERMISSION_GROUP_SPEECH = 14
    const val PERMISSION_GROUP_STORAGE = 15
    const val PERMISSION_GROUP_IGNORE_BATTERY_OPTIMIZATIONS = 16
    const val PERMISSION_GROUP_NOTIFICATION = 17
    const val PERMISSION_GROUP_ACCESS_MEDIA_LOCATION = 18
    const val PERMISSION_GROUP_ACTIVITY_RECOGNITION = 19
    const val PERMISSION_GROUP_UNKNOWN = 20
    const val PERMISSION_GROUP_BLUETOOTH = 21
    const val PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE = 22
    const val PERMISSION_GROUP_SYSTEM_ALERT_WINDOW = 23
    const val PERMISSION_GROUP_REQUEST_INSTALL_PACKAGES = 24
    const val PERMISSION_GROUP_APP_TRACK_TRANSPARENCY = 25
    const val PERMISSION_GROUP_CRITICAL_ALERTS = 26
    const val PERMISSION_GROUP_ACCESS_NOTIFICATION_POLICY = 27
    const val PERMISSION_GROUP_BLUETOOTH_SCAN = 28
    const val PERMISSION_GROUP_BLUETOOTH_ADVERTISE = 29
    const val PERMISSION_GROUP_BLUETOOTH_CONNECT = 30
    const val PERMISSION_GROUP_NEARBY_WIFI_DEVICES = 31
    const val PERMISSION_GROUP_VIDEOS = 32
    const val PERMISSION_GROUP_AUDIO = 33
    const val PERMISSION_GROUP_SCHEDULE_EXACT_ALARM = 34
    const val PERMISSION_GROUP_SENSORS_ALWAYS = 35
    const val PERMISSION_GROUP_CALENDAR_WRITE_ONLY = 36
    const val PERMISSION_GROUP_CALENDAR_FULL_ACCESS = 37
    const val PERMISSION_GROUP_ASSISTANT = 38
    const val PERMISSION_GROUP_BACKGROUND_REFRESH = 39

    const val PERMISSION_STATUS_DENIED = 0
    const val PERMISSION_STATUS_GRANTED = 1
    const val PERMISSION_STATUS_RESTRICTED = 2
    const val PERMISSION_STATUS_LIMITED = 3
    const val PERMISSION_STATUS_NEVER_ASK_AGAIN = 4

    const val SERVICE_STATUS_DISABLED = 0
    const val SERVICE_STATUS_ENABLED = 1
    const val SERVICE_STATUS_NOT_APPLICABLE = 2
}
